version: 1
default:
    httpProxy:
        activated: TRUE   #for --api
#        activated: FALSE #for --update-data
        host: proxy.nih.go.jp
        port: 8080
    workdir: /home/sasaki/git/LAPIS/work
    maxNumberWorkers: 16 
    gisaidApiConfig:
        url: https://www.epicov.org/epi3/p3/export
        username: naobumi
        password: D4fgBNUG
Lapis:
    redisHost: 127.0.0.1
    redisPort: 6789
    cacheEnabled: FALSE
    apiOpennessLevel: GISAID
    nextalignPath: /home/sasaki/git/LAPIS/app/nextalign-Linux-x86_64
    geoLocationRulesPath: /home/sasaki/git/LAPIS/server/src/main/resources/gisaid_geoLocationRules.tsv
    vineyard:
        host: 192.168.114.46
        port: 5432
        dbname: sars_cov_2
        username: y_user
        password: y_user
        schema: public
#        s3cVineyard: 
